---
- name: baitap
  hosts: all
  gather_facts: no
  
  tasks:
  	- name: dat ip cho lop
    	ios_13_interface:
      	name: loopback {{ item.number }}
        ipv4: 10.0.{{ item.number }}.1/24
      with_items:
      	- { number: 1 }
        - { number: 2 }
        - { number: 3 }
